add_library(TopoTypeScriptInit STATIC TypeScriptInitTemplateProvider.cpp)
add_library(topo::lang-typescript::TopoTypeScriptInit ALIAS TopoTypeScriptInit)

target_include_directories(TopoTypeScriptInit PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/topo-lang-typescript/topo-init>
)
target_link_libraries(TopoTypeScriptInit PUBLIC topo::lang::TopoLang)
topo_set_compiler_flags(TopoTypeScriptInit)

install(TARGETS TopoTypeScriptInit
    EXPORT topo-lang-typescriptTargets
    ARCHIVE  DESTINATION ${CMAKE_INSTALL_LIBDIR}
    INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/topo-lang-typescript/topo-init
)
install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/topo-lang-typescript/topo-init
    FILES_MATCHING PATTERN "*.h"
)
