/**
 * Graph -> .topo emission.
 *
 * This is the deterministic mapping topo-app commits to ("产出
 * .topo 的确定规则，不是黑魔法推断"), not inference:
 *
 *   - handler A's output feeds handler B's input  -> edge A -> B
 *   - logic chain A -> B -> C                      -> flow with those edges
 *   - the flow's stage topology is left to core PipelineAnalysis; the
 *     emitter only states edges, never stage numbers (a flow body
 *     accepts pipeline edges only)
 *
 * The output is human-readable and hand-editable by construction — that
 * is the topo-app design's decisive round-trip constraint, so the emitter
 * favours a stable, obvious layout over compactness.
 */

// Scalar aliases the TypeScript host binds, matching topo-init's
// `TypeScriptInitTemplateProvider::generateTypeBindings()` so emitted
// `.topo` consumes the exact stdlib vocabulary the rest of the
// toolchain expects for this host (`int`/`float` both bridge to the
// host `number`, `bool`->`boolean`, `str`->`string`).
const PREAMBLE = [
  "using int = std::typescript::number;",
  "using float = std::typescript::number;",
  "using bool = std::typescript::boolean;",
  "using str = std::typescript::string;",
].join("\n");

/** @param {import("./_graph.mjs").Graph} graph */
export function emitTopo(graph) {
  const lines = [
    "// Generated by topo-app (TypeScript). Human-readable and round-trip",
    "// safe: editing this file and reading it back yields the same",
    "// logic graph. Hand edits survive; this is a view, not an IR.",
    "",
    PREAMBLE,
    "",
    `namespace ${graph.namespace} {`,
    "  public:",
  ];
  for (const h of graph.handlers) {
    lines.push(`    ${h.signature()}`);
  }
  if (graph.flow !== null) {
    lines.push("");
    lines.push(`    flow ${graph.flow.name} {`);
    for (const e of graph.flow.edges) {
      const tgt = e.isTerminal ? "void" : e.target;
      lines.push(`      ${e.source} -> ${tgt};`);
    }
    lines.push("    }");
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}
